name: CI

on: [push, pull_request]

jobs:
  build:
    # We would like to build with v140 toolset to be compatible with both VS2017, 2019
    # But that will only be avaiilable in late november: https://github.com/actions/virtual-environments/issues/68  
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1
    
    - name: Download custom vcpkg and additional ports 
      shell: bash
      run: |
        git clone -b addGazebo10 https://github.com/traversaro/vcpkg  C:/vcpkg-robotology
        C:/vcpkg-robotology/bootstrap-vcpkg.sh
        git clone https://github.com/robotology-dependencies/robotology-vcpkg-binary-ports C:/robotology-vcpkg-binary-ports

    - name: Install vcpkg ports
      shell: bash
      run: |
        # TinyXML is not installed as a workaround for https://github.com/robotology/ycm/pull/296
        C:/vcpkg-robotology/vcpkg.exe --overlay-ports=C:/robotology-vcpkg-binary-ports install --triplet x64-windows ace freeglut gsl eigen3 ode libxml2 eigen3 opencv3 matio sdl1 sdl2 qt5-base  ipopt-binary 
        # Remove temporary files https://github.com/Microsoft/vcpkg/blob/master/docs/about/faq.md#how-can-i-remove-temporary-files
        rm -rf C:/vcpkg-robotology/buildtrees 
        C:/vcpkg-robotology/vcpkg.exe install --triplet x64-windows qt5-declarative qt5-multimedia qt5-quickcontrols2
        # Gazebo dependencies 
        rm -rf C:/vcpkg-robotology/buildtrees
        C:/vcpkg-robotology/vcpkg.exe install --triplet x64-windows boost-asio  boost-date-time  boost-filesystem  boost-forma boost-interprocess boost-iostreams boost-program-options boost-property-tree boost-regex boost-smart-ptr boost-system boost-thread boost-uuid
        rm -rf C:/vcpkg-robotology/buildtrees
        C:/vcpkg-robotology/vcpkg.exe install --triplet x64-windows bullet3 freeimage ignition-fuel-tools1 ignition-math4 ignition-msgs1 ignition-transport4
        rm -rf C:/vcpkg-robotology/buildtrees
        C:/vcpkg-robotology/vcpkg.exe install --triplet x64-windows ogre protobuf qwt sdformat6 tbb tinyxml tinyxml2 zeromq
        rm -rf C:/vcpkg-robotology/buildtrees
        C:/vcpkg-robotology/vcpkg.exe install --triplet x64-windows gazebo10
        # Remove temporary files https://github.com/Microsoft/vcpkg/blob/master/docs/about/faq.md#how-can-i-remove-temporary-files
        rm -rf C:/vcpkg-robotology/buildtrees 
        rm -rf C:/vcpkg-robotology/packages 
        rm -rf C:/vcpkg-robotology/downloads 
        
    - uses: actions/upload-artifact@master
      with:
        name: vcpkg-robotology
        path: C:/vcpkg-robotology
