name: CI

on: [push, pull_request]

jobs:
  build:
    # We would like to build with v140 toolset to be compatible with both VS2017, 2019
    # But that will only be avaiilable in late november: https://github.com/actions/virtual-environments/issues/68  
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1
  
    # Workaround for https://github.community/t5/GitHub-Actions/Windows-tests-worked-yesterday-broken-today/td-p/43574
    - name: Override bash shell PATH (windows-latest)
      run: echo "::add-path::C:\Program Files\Git\bin"
      if: matrix.os == 'windows-latest'
    
    - name: Download custom vcpkg and additional ports 
      shell: bash
      run: |
        mkdir C:/robotology
        git clone -b 2019.10 https://github.com/microsoft/vcpkg  C:/robotology/vcpkg
        C:/robotology/vcpkg/bootstrap-vcpkg.sh
        git clone https://github.com/robotology-dependencies/robotology-vcpkg-binary-ports C:/robotology-vcpkg-binary-ports

    - name: Install vcpkg ports
      shell: bash
      run: |
        # TinyXML is not installed as a workaround for https://github.com/robotology/ycm/pull/296
        C:/robotology/vcpkg/vcpkg.exe --overlay-ports=C:/robotology-vcpkg-binary-ports install --triplet x64-windows ace freeglut gsl eigen3 ode libxml2 eigen3 opencv3 matio sdl1 sdl2 qt5-base  ipopt-binary 
        # Remove temporary files https://github.com/Microsoft/vcpkg/blob/master/docs/about/faq.md#how-can-i-remove-temporary-files
        rm -rf C:/robotology/vcpkg/buildtrees 
        C:/robotology/vcpkg/vcpkg.exe --overlay-ports=C:/robotology-vcpkg-binary-ports install --triplet x64-windows qt5-declarative qt5-multimedia qt5-quickcontrols2
        # Remove temporary files https://github.com/Microsoft/vcpkg/blob/master/docs/about/faq.md#how-can-i-remove-temporary-files
        rm -rf C:/robotology/vcpkg/buildtrees 
        rm -rf C:/robotology/vcpkg/packages 
        rm -rf C:/robotology/vcpkg/downloads 
        
    - uses: actions/upload-artifact@master
      with:
        name: vcpkg-robotology
        path: C:/robotology/vcpkg
