name: CI

on: [push, pull_request]

jobs:
  build:
    # We would like to build with v140 toolset to be compatible with both VS2017, 2019
    # But that will only be avaiilable in late november: https://github.com/actions/virtual-environments/issues/68  
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1
    
    - name: Update vcpkg
      shell: bash
      run: |
        cd ${VCPKG_INSTALLATION_ROOT}
        git pull
        # Use a stable tag for reproducibility 
        git checkout 2019.10
        ./bootstrap-vcpkg.sh

    - name: Install vcpkg ports
      shell: bash
      run: |
        git clone https://github.com/robotology-dependencies/robotology-vcpkg-binary-ports C:/robotology-vcpkg-binary-ports
        # TinyXML is not installed as a workaround for https://github.com/robotology/ycm/pull/296
        vcpkg.exe --overlay-ports=C:/robotology-vcpkg-binary-ports install --triplet x64-windows eigen3 ipopt-binary 

    - uses: actions/upload-artifact@master
      with:
        name: vcpkg-robotology
        path: C:/vcpkg
